using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using System;
using System.Linq;

namespace COS_DesktopApp
{
    public partial class ucAccountDetails : DevExpress.XtraEditors.XtraUserControl
    {
        COS_DesktopApp.CanteenOrderingSystemEntities dbContext;

        private ucAccountDetails _instance;

        int addNewStatus = 0;

        public ucAccountDetails Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new ucAccountDetails();
                }
                return _instance;
            }
        }

        public ucAccountDetails()
        {

            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = new COS_DesktopApp.CanteenOrderingSystemEntities();
            
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.accounts.LoadAsync().ContinueWith(loadTask =>
            {
                this.loadRole();
                // Bind data to control when loading complete
                accountsBindingSource.DataSource = dbContext.accounts.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            

        }

        private void loadRole()
        {
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.account_role.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                account_roleBindingSource.DataSource = dbContext.account_role.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        public void ucAccountRefresh()
        {
            gridControl1.RefreshDataSource();
            gridView1.RefreshData();
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            try
            {
                DialogResult dialogResult = MessageBox.Show("Are you sure to update?", "Update", MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    dbContext.SaveChanges();
                    gridView1.ClearSorting();
                    gridView1.Columns["id"].SortOrder = DevExpress.Data.ColumnSortOrder.Ascending;
                }
                else if (dialogResult == DialogResult.No)
                {
                    if (addNewStatus != 1)
                    {
                        var changed = dbContext.ChangeTracker.Entries().Where(x => x.State != EntityState.Unchanged).ToList();
                        foreach (var obj in changed)
                        {

                            obj.CurrentValues.SetValues(obj.OriginalValues);

                            obj.State = EntityState.Unchanged;
                        }
                    }
                    else
                    {
                        gridView1.FocusedRowHandle = 0;
                        gridView1.DeleteSelectedRows();
                    }
                }
            }
            catch
            {

            }
        }

        private void windowsUIButtonPanel1_ButtonClick(object sender, DevExpress.XtraBars.Docking2010.ButtonEventArgs e)
        {
            if (e.Button == windowsUIButtonPanel1.Buttons[0])
            {
                AddUserForm addUserForm = new AddUserForm(gridView1);
                addNewStatus = 1;
                addUserForm.Show();
            }
            else if (e.Button == windowsUIButtonPanel1.Buttons[1])
            {
                DialogResult dialogResult = MessageBox.Show("Are you sure to Delete?", "Delete", MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    gridView1.SetFocusedRowCellValue(gridView1.Columns[coldeletedAt.FieldName], DateTime.Now);

                    if (gridView1.FocusedRowHandle != 0)
                    {
                        gridView1.FocusedRowHandle = 0;
                    }
                    else
                    {
                        gridView1.FocusedRowHandle = 1;
                    }
                }
                else if (dialogResult == DialogResult.No)
                {
                }
            }
        }
    }
}