using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace COS_DesktopApp
{
    public partial class ucOrder : DevExpress.XtraEditors.XtraUserControl
    {
        private ucOrder _instance;
        public ucOrder Instance
        {
            get
            {

                if (_instance == null)
                {
                    _instance = new ucOrder();

                }
                return _instance;
            }
        }
        public ucOrder()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            COS_DesktopApp.CanteenOrderingSystemEntities dbContext = new COS_DesktopApp.CanteenOrderingSystemEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.orders.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    ordersBindingSource.DataSource = dbContext.orders.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
