using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Columns;

namespace COS_DesktopApp
{
    public partial class ucProduct : DevExpress.XtraEditors.XtraUserControl
    {
        COS_DesktopApp.CanteenOrderingSystemEntities dbContext;

        private ucProduct _instance;
        public ucProduct Instance
        {
            get
            {

                if (_instance == null)
                {
                    _instance = new ucProduct();

                }
                return _instance;
            }
        }

        public ucProduct()
        {
            try
            {


                // This line of code is generated by Data Source Configuration Wizard
                // Instantiate a new DBContext
                dbContext = new COS_DesktopApp.CanteenOrderingSystemEntities();

                // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
                dbContext.products.LoadAsync().ContinueWith(loadTask =>
                {

                    this.loadCompany();


                    // Bind data to control when loading complete
                    productsBindingSource.DataSource = dbContext.products.Local.ToBindingList();

                }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            }
            catch
            {

            }
            InitializeComponent();


        }

        public void loadCompany()
        {
            dbContext.companies.LoadAsync().ContinueWith(loadTask =>
            {
                this.loadType();
                // Bind data to control when loading complete
                companiesBindingSource.DataSource = dbContext.companies.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        public void loadType()
        {
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.products_type.LoadAsync().ContinueWith(loadTask =>
            {
                this.loadOrigin();
                // Bind data to control when loading complete
                products_typeBindingSource.DataSource = dbContext.products_type.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        public void loadOrigin()
        {
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.origins.LoadAsync().ContinueWith(loadTask =>
            {
                this.loadSugar();
                // Bind data to control when loading complete
                originsBindingSource.DataSource = dbContext.origins.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        public void loadSugar()
        {
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.sugar_level.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                sugar_levelBindingSource.DataSource = dbContext.sugar_level.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btn_ButtonClick(object sender, DevExpress.XtraBars.Docking2010.ButtonEventArgs e)
        {
            if (e.Button == btn.Buttons[0])
            {
                gridView1.AddNewRow();
                gridView1.ShowEditForm();
            }
            else if (e.Button == btn.Buttons[1])
            {
                DialogResult dialogResult = MessageBox.Show("Are you sure to Delete?", "Delete", MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    gridView1.SetFocusedRowCellValue(gridView1.Columns[coldeletedAt.FieldName], DateTime.Now);
                    dbContext.SaveChanges();
                    if (gridView1.FocusedRowHandle != 0)
                    {
                        gridView1.FocusedRowHandle = 0;
                    }
                    else
                    {
                        gridView1.FocusedRowHandle = 1;
                    }
                }
                else if (dialogResult == DialogResult.No)
                {
                }
            }
            else if (e.Button == btn.Buttons[2])
            {
                var dialog = new SaveFileDialog();
                dialog.Title = "Export";
                dialog.Filter = @"Microsoft Excel|*.xlsx";
                if (dialog.ShowDialog() == DialogResult.OK)
                {
                    DevExpress.Export.ExportSettings.DefaultExportType = DevExpress.Export.ExportType.WYSIWYG;
                    gridControl1.ExportToXlsx(dialog.FileName);
                    XtraMessageBox.Show("Success");
                }

            }
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            try
            {
                DialogResult dialogResult = MessageBox.Show("Are you sure to update?", "Update", MessageBoxButtons.YesNo);
                if (dialogResult == DialogResult.Yes)
                {
                    dbContext.SaveChanges();
                }
                else if (dialogResult == DialogResult.No)
                {
                    var changed = dbContext.ChangeTracker.Entries().Where(x => x.State != EntityState.Unchanged).ToList();
                    foreach (var obj in changed)
                    {

                        obj.CurrentValues.SetValues(obj.OriginalValues);

                        obj.State = EntityState.Unchanged;
                    }

                }
            }
            catch
            {

            }

        }


    }
}
