//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COS_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.carts = new HashSet<cart>();
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Remote("checkEmail", "Authentication", HttpMethod = "POST", ErrorMessage = "Email already exists in database.")]
        public string email { get; set; }
       
        public string password { get; set; }
        [Required]
        [RegularExpression(@"^([A-Za-z]+( [A-Za-z]+)+)$", ErrorMessage = "Full name must only in alphabets and  more than two words")]
        public string fullname { get; set; }
        [Required]
        public System.DateTime birthday { get; set; }
        [Required]
        [RegularExpression(@"^0\d{9}$", ErrorMessage = "Phone number has 10 digits and start with 0")]
        public string phonenumber { get; set; }
        public int id_role { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
    
        public virtual account_role account_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
